### ISSUE TITLE
Specifying signing service at publish time is inconsistent and a bad user experience

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp_deb#641]
We're using a signing service to sign our repos. It looks like for pulp_deb, you have to pass the signing service in at publish time. This is inconsistent with how pulp_rpm does it (there you set the signing service info on the repo):

https://docs.pulpproject.org/pulp_rpm/workflows/metadata_signing.html

And it's also a hassle because that means the user has to track which signing service goes with which repository somehow.

Would pulp_deb be open to a PR that adds a `signing_service` field to the repository? Perhaps it could be used by default and if signing_service is specified at publish time, it would override the signing_service field on repository.

**Comment by mdellweg** [comment]
This is a perfect option to be on the (no longer existent) `Publisher`. But I agree having an option on the `Repository` with the possibility to overrule on `publish` sounds like something we discussed some time ago. This also looks necessary for any reasonable `auto-publish` implementation.

**Comment by quba42** [comment]
I am certainly open to a "convenience" field on the repository, that can be overridden using the existing publish time field. This adds convenience and pulp_rpm similarity without impacting the existing workflow. Since we are used to the existing workflow, this is not a priority for us, but we would be happy to review an external contribution. This does not sound like a feature that would be very hard to implement, review, and test.

It should probably be followed up with a change in Pulp CLI (deb) as well: https://github.com/pulp/pulp-cli-deb

**Comment by sdherr** [comment]
It's also possible that someone might want to sign different releases inside a repo with different keys/services. This is not currently possible in `pulp_deb`, however if we're adding a new field to the Repo anyway then it's pretty easy to enable it by allowing the user to override it with another filed on the Release. In order to guarantee consistency with current behavior I think if `signing_service` is provided on the Publication creation request then it should override everything else.

**Comment by quba42** [comment]
[pulp-cli-deb issue](https://github.com/pulp/pulp-cli-deb/issues/54) to go with this issue.
