### ISSUE TITLE
duplicate key value violates unique constraint "core_publishedmetadata_publication_id_relative__60dd832b_uniq"

### ISSUE THREAD

**Issue by rossengeorgiev** [pulp/pulp_deb#648]
**Version**
`katello-4.4.1-1.el7.noarch`

**Describe the bug**
```
Errors:

duplicate key value violates unique constraint "core_publishedmetadata_publication_id_relative__60dd832b_uniq"
DETAIL:  Key (publication_id, relative_path)=(2facde6a-9f6f-46ce-9519-c59825a96fd6, dists/focal/main/binary-amd64/Packages) already exists.
```

**To Reproduce**
1. Create deb repo with upstream `https://apt.releases.hashicorp.com` with `focal`, `main`, `amd64`
2. Attempt sync
3. Sync completed with warning, giving the above messages

Note: subsequent sync will succeed and not display any errors

**Expected behavior**
Successful repo sync

**Comment by quba42** [comment]
Successfully reproduced using:
```
ENTITIES_NAME='test'
REMOTE_OPTIONS='--url=https://apt.releases.hashicorp.com --distribution=focal --component=main --architecture=amd64 --policy=on_demand'
oci-env pulp deb remote create --name=${ENTITIES_NAME} ${REMOTE_OPTIONS}
oci-env pulp deb repository create --name=${ENTITIES_NAME} --remote=${ENTITIES_NAME}
oci-env pulp deb repository sync --name=${ENTITIES_NAME}
oci-env pulp deb publication create --repository=${ENTITIES_NAME} --simple --structured
```

**Comment by quba42** [comment]
Ok, I have analyzed the problem: The upstream repo includes both a `main` component, and a `main` component with a path prefix (`_temp-1646089102832_/focal/main`). Path prefixes before a component is normally only allowed if the distribution contains a Release file located more than one folder layer below `dists/` which is not the case here. This strikes me as an undefined repo format that happens to work with APT, but clashes with how we implemented nested Release files in pulp_deb.

I will need to investigate further if I can come up with an implementation that satisfies both repo formats.

**Comment by rossengeorgiev** [comment]
@quba42 is it worth raising an issue with hashicorp about the repo format? That `_temp-....` doesn't look right. I wish their repo was browsable, would make things easier.

**Comment by quba42** [comment]
@rossengeorgiev I think the `_temp-1646089102832_/focal/main` looks like something they forgot to clean up, and also is not something one _should_ be doing, since it really clashes with the [APT repo specification](https://wiki.debian.org/DebianRepository/Format#Components). So yes, it is worth opening an issue with hashicorp. If you do, feel free to drop a link to the hashicorp issue here as well (if it is publicly viewable).

I have also looked into how hard it would be to make pulp_deb robust with respect to this particular "repo weirdness", and unfortunately it looks like it will be quite difficult to do, without breaking anything else. It is currently uncertain if and when we might work on a pulp_deb side fix. <= Another reason why it would be great if hashicorp could simply fix this on the repo side.

**Comment by rossengeorgiev** [comment]
That's what I thought. They are on Github, so I'll raise an issue on one of their products, and see what they say, as the repo is shared across all of them.

**Comment by quba42** [comment]
I tried opening a thread in the HashiCorp forum (in a random product category): https://discuss.hashicorp.com/t/how-can-i-get-in-touch-with-the-hashicorp-linux-packaging-team/51063

Hopefully somebody will put me in contact with a member of their packaging team.

**Comment by quba42** [comment]
Looks like HashiCorp fixed the repo!

**Comment by rossengeorgiev** [comment]
That was quick, but now I get 
![image](https://user-images.githubusercontent.com/2720787/223364042-c4f6cc72-906d-4733-87a4-4b3c296dde14.png)

**Comment by rossengeorgiev** [comment]
My GPG key was out of date. Sync'd successfully with the new key. Thanks for the help @quba42
