### ISSUE TITLE
Autopublish for Debian plugin like the RPM one does

### ISSUE THREAD

**Issue by Catman155** [pulp/pulp_deb#662]
**Is your feature request related to a problem? Please describe.**
I don't really know if it is a bug, but on the RPM plugin when I set the repository to autopublish, I only have to add the repository to the distribution and every time I add/remove content from the repository, the new version gets distributed automatically.

**Describe the solution you'd like**
I would like to set the autopublish on the repository like in the RPM plugin.

**Describe alternatives you've considered**
I considered using publications. but those are usually more actions than needed I would say.

**Additional context**
The RPM plugin has an implementation that works as the solution described above.

**Comment by quba42** [comment]
When the autopublish/distribute feature was new, I tried implementing it for pulp_deb. However I quickly ran into design issues with how to decide whether a given distribution should use verbatim publisher or APT publisher (using what publication options) and since this is not a high priority feature for us, I gave up at that point.

This continues to be a nice to have feature, that we may eventually get around to, but it isn't currently on our roadmap.

**Comment by daviddavis** [comment]
We'd also like to have this feature. 

At least with pulp_file, [autopublish options (ie manifest name) are stored on the repository model](https://github.com/pulp/pulp_file/blob/11bec639d53bfcabed4d1cc3910c45b70eb4f48d/pulp_file/app/models.py#L69). Not sure if that might help solve the problem?

**Comment by Catman155** [comment]
Is it really that hard to implement? I mean. it should be an option on the repository model I think, like on the RPM repository model. And then just making a publish when a new version is created and the option on the repository is on. and then have the distribution get the latest publish for the set repostiory on the distribution.
